
#where are skdb packages stored?
#url: http://www.debian.org/doc/packaging-manuals/fhs/fhs-2.3.html
package dir: /usr/local/share/skdb/

#where are packages available from the web?
repositories:
    - http://adl.serveftp.org/skdb-packages/

